version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fastlane
    versions:
    - 2.172.0
    - 2.173.0
    - 2.174.0
    - 2.175.0
    - 2.176.0
    - 2.177.0
    - 2.178.0
    - 2.179.0
    - 2.180.0
    - 2.180.1
  - dependency-name: fir-cli
    versions:
    - 2.0.11
    - 2.0.12
