  
  

  
  
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

  

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NCProtoChatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NCProtoChatRoot : GPBRootObject
@end

#pragma mark - NCProtoText

typedef GPB_ENUM(NCProtoText_FieldNumber) {
  NCProtoText_FieldNumber_Content = 1,
};

@interface NCProtoText : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@end

#pragma mark - NCProtoAudio

typedef GPB_ENUM(NCProtoAudio_FieldNumber) {
  NCProtoAudio_FieldNumber_Content = 1,
  NCProtoAudio_FieldNumber_PlayTime = 2,
};

@interface NCProtoAudio : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

 
@property(nonatomic, readwrite) uint32_t playTime;

@end

#pragma mark - NCProtoImage

typedef GPB_ENUM(NCProtoImage_FieldNumber) {
  NCProtoImage_FieldNumber_Id_p = 1,
  NCProtoImage_FieldNumber_Width = 2,
  NCProtoImage_FieldNumber_Height = 3,
};

@interface NCProtoImage : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) uint32_t width;

@property(nonatomic, readwrite) uint32_t height;

@end

#pragma mark - NCProtoVideo

typedef GPB_ENUM(NCProtoVideo_FieldNumber) {
  NCProtoVideo_FieldNumber_Id_p = 1,
  NCProtoVideo_FieldNumber_PlayTime = 2,
};

@interface NCProtoVideo : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

 
@property(nonatomic, readwrite) uint32_t playTime;

@end

#pragma mark - NCProtoFile

typedef GPB_ENUM(NCProtoFile_FieldNumber) {
  NCProtoFile_FieldNumber_Id_p = 1,
  NCProtoFile_FieldNumber_Name = 2,
  NCProtoFile_FieldNumber_Size = 3,
};

@interface NCProtoFile : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

 
@property(nonatomic, readwrite) uint32_t size;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

  
