// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NCProtoChatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NCProtoChatRoot : GPBRootObject
@end

#pragma mark - NCProtoText

typedef GPB_ENUM(NCProtoText_FieldNumber) {
  NCProtoText_FieldNumber_Content = 1,
};

@interface NCProtoText : GPBMessage

/** 文本内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@end

#pragma mark - NCProtoAudio

typedef GPB_ENUM(NCProtoAudio_FieldNumber) {
  NCProtoAudio_FieldNumber_Content = 1,
  NCProtoAudio_FieldNumber_PlayTime = 2,
};

@interface NCProtoAudio : GPBMessage

/** 音频字节流 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

/** 播放时长 */
@property(nonatomic, readwrite) uint32_t playTime;

@end

#pragma mark - NCProtoImage

typedef GPB_ENUM(NCProtoImage_FieldNumber) {
  NCProtoImage_FieldNumber_Id_p = 1,
  NCProtoImage_FieldNumber_Width = 2,
  NCProtoImage_FieldNumber_Height = 3,
};

@interface NCProtoImage : GPBMessage

/** 图片ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) uint32_t width;

@property(nonatomic, readwrite) uint32_t height;

@end

#pragma mark - NCProtoVideo

typedef GPB_ENUM(NCProtoVideo_FieldNumber) {
  NCProtoVideo_FieldNumber_Id_p = 1,
  NCProtoVideo_FieldNumber_PlayTime = 2,
};

@interface NCProtoVideo : GPBMessage

/** 视频ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 播放时长 */
@property(nonatomic, readwrite) uint32_t playTime;

@end

#pragma mark - NCProtoFile

typedef GPB_ENUM(NCProtoFile_FieldNumber) {
  NCProtoFile_FieldNumber_Id_p = 1,
  NCProtoFile_FieldNumber_Name = 2,
  NCProtoFile_FieldNumber_Size = 3,
};

@interface NCProtoFile : GPBMessage

/** 文件ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 文件名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 文件大小 */
@property(nonatomic, readwrite) uint32_t size;

@end

#pragma mark - NCProtoNews

typedef GPB_ENUM(NCProtoNews_FieldNumber) {
  NCProtoNews_FieldNumber_Title = 1,
  NCProtoNews_FieldNumber_Description_p = 2,
  NCProtoNews_FieldNumber_URL = 3,
  NCProtoNews_FieldNumber_PicURL = 4,
};

@interface NCProtoNews : GPBMessage

/** 标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *title;

/** 描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *description_p;

/** 跳转url */
@property(nonatomic, readwrite, copy, null_resettable) NSData *URL;

/** 图片url */
@property(nonatomic, readwrite, copy, null_resettable) NSData *picURL;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
