




#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif



#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum NCProtoChatType

typedef GPB_ENUM(NCProtoChatType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NCProtoChatType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NCProtoChatType_ChatTypeUnspecified = 0,
  NCProtoChatType_ChatTypeSingle = 1,
  NCProtoChatType_ChatTypeGroup = 2,
};

GPBEnumDescriptor *NCProtoChatType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NCProtoChatType_IsValidValue(int32_t value);

#pragma mark - Enum NCProtoActionType

typedef GPB_ENUM(NCProtoActionType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NCProtoActionType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NCProtoActionType_ActionTypeUnspecified = 0,
  NCProtoActionType_ActionTypeAdd = 1,
  NCProtoActionType_ActionTypeDelete = 2,
};

GPBEnumDescriptor *NCProtoActionType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NCProtoActionType_IsValidValue(int32_t value);

#pragma mark - Enum NCProtoOrderBizStatus


typedef GPB_ENUM(NCProtoOrderBizStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NCProtoOrderBizStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NCProtoOrderBizStatus_OrderBizStatusUnspecified = 0,
  NCProtoOrderBizStatus_OrderBizStatusOngoing = 1,
  NCProtoOrderBizStatus_OrderBizStatusSuccess = 2,
  NCProtoOrderBizStatus_OrderBizStatusFailed = 3,
};

GPBEnumDescriptor *NCProtoOrderBizStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NCProtoOrderBizStatus_IsValidValue(int32_t value);

#pragma mark - NCProtoCommonTypesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NCProtoCommonTypesRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop


