




#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif



#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NCProtoContactsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NCProtoContactsRoot : GPBRootObject
@end

#pragma mark - NCProtoContacts

typedef GPB_ENUM(NCProtoContacts_FieldNumber) {
  NCProtoContacts_FieldNumber_PubKey = 1,
  NCProtoContacts_FieldNumber_Summary = 2,
  NCProtoContacts_FieldNumber_Content = 3,
};

@interface NCProtoContacts : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *pubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSData *summary;

@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop


