




#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif




CF_EXTERN_C_BEGIN

@class NCProtoHead;
@class NCProtoNetMsg;

NS_ASSUME_NONNULL_BEGIN


typedef GPB_ENUM(NCProtoDeviceType) {
  NCProtoDeviceType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NCProtoDeviceType_Ios = 0,
  NCProtoDeviceType_Android = 1,
  NCProtoDeviceType_Pc = 2,
};

GPBEnumDescriptor *NCProtoDeviceType_EnumDescriptor(void);

BOOL NCProtoDeviceType_IsValidValue(int32_t value);


@interface NCProtoNetMsgRoot : GPBRootObject
@end


typedef GPB_ENUM(NCProtoNetMsg_FieldNumber) {
  NCProtoNetMsg_FieldNumber_Name = 1,
  NCProtoNetMsg_FieldNumber_Data_p = 2,
  NCProtoNetMsg_FieldNumber_Compress = 3,
  NCProtoNetMsg_FieldNumber_Head = 4,
};

@interface NCProtoNetMsg : GPBMessage


@property(nonatomic, readwrite, copy, null_resettable) NSString *name;


@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;


@property(nonatomic, readwrite) BOOL compress;


@property(nonatomic, readwrite, strong, null_resettable) NCProtoHead *head;

@property(nonatomic, readwrite) BOOL hasHead;

@end


typedef GPB_ENUM(NCProtoHead_FieldNumber) {
  NCProtoHead_FieldNumber_FromPubKey = 1,
  NCProtoHead_FieldNumber_ToPubKey = 2,
  NCProtoHead_FieldNumber_Signature = 3,
  NCProtoHead_FieldNumber_MsgTime = 4,
};

@interface NCProtoHead : GPBMessage


@property(nonatomic, readwrite, copy, null_resettable) NSData *fromPubKey;


@property(nonatomic, readwrite, copy, null_resettable) NSData *toPubKey;


@property(nonatomic, readwrite, copy, null_resettable) NSData *signature;


@property(nonatomic, readwrite) uint64_t msgTime;

@end


@interface NCProtoHeartbeat : GPBMessage

@end


typedef GPB_ENUM(NCProtoClientReceipt_FieldNumber) {
  NCProtoClientReceipt_FieldNumber_Result = 1,
};

@interface NCProtoClientReceipt : GPBMessage


@property(nonatomic, readwrite) int32_t result;

@end


typedef GPB_ENUM(NCProtoServerReceipt_FieldNumber) {
  NCProtoServerReceipt_FieldNumber_Result = 1,
};

@interface NCProtoServerReceipt : GPBMessage


@property(nonatomic, readwrite) int32_t result;

@end


typedef GPB_ENUM(NCProtoRegisterReq_FieldNumber) {
  NCProtoRegisterReq_FieldNumber_DeviceType = 1,
  NCProtoRegisterReq_FieldNumber_Version = 2,
};

@interface NCProtoRegisterReq : GPBMessage


@property(nonatomic, readwrite) NCProtoDeviceType deviceType;


@property(nonatomic, readwrite) uint32_t version;

@end

int32_t NCProtoRegisterReq_DeviceType_RawValue(NCProtoRegisterReq *message);
void SetNCProtoRegisterReq_DeviceType_RawValue(NCProtoRegisterReq *message, int32_t value);


typedef GPB_ENUM(NCProtoRegisterRsp_FieldNumber) {
  NCProtoRegisterRsp_FieldNumber_Result = 1,
  NCProtoRegisterRsp_FieldNumber_ServerPubKey = 2,
};

@interface NCProtoRegisterRsp : GPBMessage


@property(nonatomic, readwrite) int32_t result;


@property(nonatomic, readwrite, copy, null_resettable) NSData *serverPubKey;

@end


typedef GPB_ENUM(NCProtoAppleIdBind_FieldNumber) {
  NCProtoAppleIdBind_FieldNumber_AppleId = 2,
};

@interface NCProtoAppleIdBind : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appleId;

@end


typedef GPB_ENUM(NCProtoAppleIdUnbind_FieldNumber) {
  NCProtoAppleIdUnbind_FieldNumber_AppleId = 2,
};

@interface NCProtoAppleIdUnbind : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appleId;

@end


typedef GPB_ENUM(NCProtoCacheMsgReq_FieldNumber) {
  NCProtoCacheMsgReq_FieldNumber_RoundId = 1,
  NCProtoCacheMsgReq_FieldNumber_Time = 2,
  NCProtoCacheMsgReq_FieldNumber_Hash_p = 3,
  NCProtoCacheMsgReq_FieldNumber_Size = 4,
};

@interface NCProtoCacheMsgReq : GPBMessage


@property(nonatomic, readwrite) uint32_t roundId;


@property(nonatomic, readwrite) uint64_t time;


@property(nonatomic, readwrite) uint64_t hash_p;


@property(nonatomic, readwrite) uint32_t size;

@end


typedef GPB_ENUM(NCProtoCacheMsgRsp_FieldNumber) {
  NCProtoCacheMsgRsp_FieldNumber_RoundId = 1,
  NCProtoCacheMsgRsp_FieldNumber_MsgsArray = 2,
};

@interface NCProtoCacheMsgRsp : GPBMessage


@property(nonatomic, readwrite) uint32_t roundId;


@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NCProtoNetMsg*> *msgsArray;

@property(nonatomic, readonly) NSUInteger msgsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END



