// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class NCProtoOrder;
GPB_ENUM_FWD_DECLARE(NCProtoOrderBizStatus);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum NCProtoPayReason

typedef GPB_ENUM(NCProtoPayReason) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NCProtoPayReason_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NCProtoPayReason_PayReasonUnspecified = 0,
  NCProtoPayReason_PayReasonRecallMsg = 1,
};

GPBEnumDescriptor *NCProtoPayReason_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NCProtoPayReason_IsValidValue(int32_t value);

#pragma mark - Enum NCProtoPayMethod

typedef GPB_ENUM(NCProtoPayMethod) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NCProtoPayMethod_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NCProtoPayMethod_PayMethodUnspecified = 0,
  NCProtoPayMethod_PayMethodAlipay = 1,
};

GPBEnumDescriptor *NCProtoPayMethod_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NCProtoPayMethod_IsValidValue(int32_t value);

#pragma mark - NCProtoPayRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NCProtoPayRoot : GPBRootObject
@end

#pragma mark - NCProtoPayPriceReq

typedef GPB_ENUM(NCProtoPayPriceReq_FieldNumber) {
  NCProtoPayPriceReq_FieldNumber_Reason = 1,
};

@interface NCProtoPayPriceReq : GPBMessage

@property(nonatomic, readwrite) NCProtoPayReason reason;

@end

/**
 * Fetches the raw value of a @c NCProtoPayPriceReq's @c reason property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoPayPriceReq_Reason_RawValue(NCProtoPayPriceReq *message);
/**
 * Sets the raw value of an @c NCProtoPayPriceReq's @c reason property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoPayPriceReq_Reason_RawValue(NCProtoPayPriceReq *message, int32_t value);

#pragma mark - NCProtoPayPriceRsp

typedef GPB_ENUM(NCProtoPayPriceRsp_FieldNumber) {
  NCProtoPayPriceRsp_FieldNumber_OrignalPrice = 1,
  NCProtoPayPriceRsp_FieldNumber_CurrentPrice = 2,
  NCProtoPayPriceRsp_FieldNumber_Discount = 3,
  NCProtoPayPriceRsp_FieldNumber_Description_p = 4,
};

@interface NCProtoPayPriceRsp : GPBMessage

/** 正常价格 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orignalPrice;

/** 当前价格 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *currentPrice;

/** 是否打折 */
@property(nonatomic, readwrite) BOOL discount;

/** 价格描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@end

#pragma mark - NCProtoPayOrderReq

typedef GPB_ENUM(NCProtoPayOrderReq_FieldNumber) {
  NCProtoPayOrderReq_FieldNumber_Reason = 1,
  NCProtoPayOrderReq_FieldNumber_Method = 2,
  NCProtoPayOrderReq_FieldNumber_Subject = 3,
  NCProtoPayOrderReq_FieldNumber_Amount = 4,
  NCProtoPayOrderReq_FieldNumber_Description_p = 5,
  NCProtoPayOrderReq_FieldNumber_BizContent = 6,
};

@interface NCProtoPayOrderReq : GPBMessage

/** 支付原因 */
@property(nonatomic, readwrite) NCProtoPayReason reason;

/** 支付方式 */
@property(nonatomic, readwrite) NCProtoPayMethod method;

/** 支付说明 (例如： 消息撤回) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subject;

/** 支付金额 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *amount;

/** 交易业务描述，例如消息撤回可以填对方的地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

/** 业务信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *bizContent;

@end

/**
 * Fetches the raw value of a @c NCProtoPayOrderReq's @c reason property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoPayOrderReq_Reason_RawValue(NCProtoPayOrderReq *message);
/**
 * Sets the raw value of an @c NCProtoPayOrderReq's @c reason property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoPayOrderReq_Reason_RawValue(NCProtoPayOrderReq *message, int32_t value);

/**
 * Fetches the raw value of a @c NCProtoPayOrderReq's @c method property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoPayOrderReq_Method_RawValue(NCProtoPayOrderReq *message);
/**
 * Sets the raw value of an @c NCProtoPayOrderReq's @c method property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoPayOrderReq_Method_RawValue(NCProtoPayOrderReq *message, int32_t value);

#pragma mark - NCProtoPayOrderRsp

typedef GPB_ENUM(NCProtoPayOrderRsp_FieldNumber) {
  NCProtoPayOrderRsp_FieldNumber_PayURL = 1,
  NCProtoPayOrderRsp_FieldNumber_OutTradeNo = 2,
};

@interface NCProtoPayOrderRsp : GPBMessage

/** 支付URL */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payURL;

/** 支付业务订单号，非支付宝订单 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *outTradeNo;

@end

#pragma mark - NCProtoOrder

typedef GPB_ENUM(NCProtoOrder_FieldNumber) {
  NCProtoOrder_FieldNumber_Reason = 1,
  NCProtoOrder_FieldNumber_Method = 2,
  NCProtoOrder_FieldNumber_Subject = 3,
  NCProtoOrder_FieldNumber_Amount = 4,
  NCProtoOrder_FieldNumber_Description_p = 5,
  NCProtoOrder_FieldNumber_BizContent = 6,
  NCProtoOrder_FieldNumber_OutTradeNo = 7,
  NCProtoOrder_FieldNumber_TradeNo = 8,
  NCProtoOrder_FieldNumber_TradeStatus = 9,
  NCProtoOrder_FieldNumber_GmtCreate = 10,
  NCProtoOrder_FieldNumber_GmtRefund = 11,
  NCProtoOrder_FieldNumber_GmtPayment = 12,
  NCProtoOrder_FieldNumber_GmtClose = 13,
  NCProtoOrder_FieldNumber_BizStatus = 14,
};

@interface NCProtoOrder : GPBMessage

@property(nonatomic, readwrite) NCProtoPayReason reason;

@property(nonatomic, readwrite) NCProtoPayMethod method;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subject;

@property(nonatomic, readwrite, copy, null_resettable) NSString *amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSData *bizContent;

/** 支付业务订单号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *outTradeNo;

/** 支付系统交易号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tradeNo;

/** 交易状态 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tradeStatus;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gmtCreate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gmtRefund;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gmtPayment;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gmtClose;

@property(nonatomic, readwrite) enum NCProtoOrderBizStatus bizStatus;

@end

/**
 * Fetches the raw value of a @c NCProtoOrder's @c reason property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoOrder_Reason_RawValue(NCProtoOrder *message);
/**
 * Sets the raw value of an @c NCProtoOrder's @c reason property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoOrder_Reason_RawValue(NCProtoOrder *message, int32_t value);

/**
 * Fetches the raw value of a @c NCProtoOrder's @c method property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoOrder_Method_RawValue(NCProtoOrder *message);
/**
 * Sets the raw value of an @c NCProtoOrder's @c method property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoOrder_Method_RawValue(NCProtoOrder *message, int32_t value);

/**
 * Fetches the raw value of a @c NCProtoOrder's @c bizStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoOrder_BizStatus_RawValue(NCProtoOrder *message);
/**
 * Sets the raw value of an @c NCProtoOrder's @c bizStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoOrder_BizStatus_RawValue(NCProtoOrder *message, int32_t value);

#pragma mark - NCProtoQueryOrderReq

typedef GPB_ENUM(NCProtoQueryOrderReq_FieldNumber) {
  NCProtoQueryOrderReq_FieldNumber_OutTradeNo = 1,
};

@interface NCProtoQueryOrderReq : GPBMessage

/** 支付业务订单号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *outTradeNo;

@end

#pragma mark - NCProtoQueryOrderRsp

typedef GPB_ENUM(NCProtoQueryOrderRsp_FieldNumber) {
  NCProtoQueryOrderRsp_FieldNumber_Order = 1,
  NCProtoQueryOrderRsp_FieldNumber_TradeSuccess = 2,
};

@interface NCProtoQueryOrderRsp : GPBMessage

/** 订单详情 */
@property(nonatomic, readwrite, strong, null_resettable) NCProtoOrder *order;
/** Test to see if @c order has been set. */
@property(nonatomic, readwrite) BOOL hasOrder;

/** 交易是否成功 */
@property(nonatomic, readwrite) BOOL tradeSuccess;

@end

#pragma mark - NCProtoOrderHistoryReq

typedef GPB_ENUM(NCProtoOrderHistoryReq_FieldNumber) {
  NCProtoOrderHistoryReq_FieldNumber_BeginTime = 1,
  NCProtoOrderHistoryReq_FieldNumber_EndTime = 2,
};

@interface NCProtoOrderHistoryReq : GPBMessage

@property(nonatomic, readwrite) int64_t beginTime;

@property(nonatomic, readwrite) int64_t endTime;

@end

#pragma mark - NCProtoOrderHistoryRsp

typedef GPB_ENUM(NCProtoOrderHistoryRsp_FieldNumber) {
  NCProtoOrderHistoryRsp_FieldNumber_OrdersArray = 1,
};

@interface NCProtoOrderHistoryRsp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NCProtoOrder*> *ordersArray;
/** The number of items in @c ordersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ordersArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
