




#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif



#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class NCProtoRecallMsg;
GPB_ENUM_FWD_DECLARE(NCProtoChatType);
GPB_ENUM_FWD_DECLARE(NCProtoOrderBizStatus);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NCProtoRecallMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NCProtoRecallMsgRoot : GPBRootObject
@end

#pragma mark - NCProtoRecallMsgReq

typedef GPB_ENUM(NCProtoRecallMsgReq_FieldNumber) {
  NCProtoRecallMsgReq_FieldNumber_FromAddr = 1,
  NCProtoRecallMsgReq_FieldNumber_FromCompressedPubKey = 2,
  NCProtoRecallMsgReq_FieldNumber_ToCompressedPubKey = 3,
  NCProtoRecallMsgReq_FieldNumber_ChatType = 4,
  NCProtoRecallMsgReq_FieldNumber_Timestamp = 5,
  NCProtoRecallMsgReq_FieldNumber_R = 6,
  NCProtoRecallMsgReq_FieldNumber_S = 7,
  NCProtoRecallMsgReq_FieldNumber_V = 8,
  NCProtoRecallMsgReq_FieldNumber_OutTradeNo = 9,
};

/**
 * http request/response messages
 **/
@interface NCProtoRecallMsgReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *fromAddr;

@property(nonatomic, readwrite, copy, null_resettable) NSData *fromCompressedPubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toCompressedPubKey;

/** 撤回消息类型：单聊或群聊 */
@property(nonatomic, readwrite) enum NCProtoChatType chatType;


@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSData *r;

@property(nonatomic, readwrite, copy, null_resettable) NSData *s;

@property(nonatomic, readwrite, copy, null_resettable) NSData *v;


@property(nonatomic, readwrite, copy, null_resettable) NSString *outTradeNo;

@end

/**
 * Fetches the raw value of a @c NCProtoRecallMsgReq's @c chatType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoRecallMsgReq_ChatType_RawValue(NCProtoRecallMsgReq *message);
/**
 * Sets the raw value of an @c NCProtoRecallMsgReq's @c chatType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoRecallMsgReq_ChatType_RawValue(NCProtoRecallMsgReq *message, int32_t value);

#pragma mark - NCProtoRecallMsgRsp

typedef GPB_ENUM(NCProtoRecallMsgRsp_FieldNumber) {
  NCProtoRecallMsgRsp_FieldNumber_TxHash = 1,
};

@interface NCProtoRecallMsgRsp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *txHash;

@end

#pragma mark - NCProtoRecallMsg

typedef GPB_ENUM(NCProtoRecallMsg_FieldNumber) {
  NCProtoRecallMsg_FieldNumber_FromPubKey = 1,
  NCProtoRecallMsg_FieldNumber_ToPubKey = 2,
  NCProtoRecallMsg_FieldNumber_ChatType = 3,
  NCProtoRecallMsg_FieldNumber_Timestamp = 4,
};

@interface NCProtoRecallMsg : GPBMessage


@property(nonatomic, readwrite, copy, null_resettable) NSData *fromPubKey;


@property(nonatomic, readwrite, copy, null_resettable) NSData *toPubKey;

/** 撤回消息类型：单聊或群聊 */
@property(nonatomic, readwrite) enum NCProtoChatType chatType;


@property(nonatomic, readwrite) int64_t timestamp;

@end

/**
 * Fetches the raw value of a @c NCProtoRecallMsg's @c chatType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoRecallMsg_ChatType_RawValue(NCProtoRecallMsg *message);
/**
 * Sets the raw value of an @c NCProtoRecallMsg's @c chatType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoRecallMsg_ChatType_RawValue(NCProtoRecallMsg *message, int32_t value);

#pragma mark - NCProtoQueryRecallMsgReq

typedef GPB_ENUM(NCProtoQueryRecallMsgReq_FieldNumber) {
  NCProtoQueryRecallMsgReq_FieldNumber_BeginTime = 1,
  NCProtoQueryRecallMsgReq_FieldNumber_EndTime = 2,
  NCProtoQueryRecallMsgReq_FieldNumber_GroupPubKeysArray = 3,
};

@interface NCProtoQueryRecallMsgReq : GPBMessage


@property(nonatomic, readwrite) int64_t beginTime;


@property(nonatomic, readwrite) int64_t endTime;


@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *groupPubKeysArray;
/** The number of items in @c groupPubKeysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupPubKeysArray_Count;

@end

#pragma mark - NCProtoQueryRecallMsgRsp

typedef GPB_ENUM(NCProtoQueryRecallMsgRsp_FieldNumber) {
  NCProtoQueryRecallMsgRsp_FieldNumber_RecallMsgsArray = 1,
};

@interface NCProtoQueryRecallMsgRsp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NCProtoRecallMsg*> *recallMsgsArray;
/** The number of items in @c recallMsgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger recallMsgsArray_Count;

@end

#pragma mark - NCProtoQueryRecallStatusReq

typedef GPB_ENUM(NCProtoQueryRecallStatusReq_FieldNumber) {
  NCProtoQueryRecallStatusReq_FieldNumber_RelatedPubKey = 1,
  NCProtoQueryRecallStatusReq_FieldNumber_ChatType = 2,
};

@interface NCProtoQueryRecallStatusReq : GPBMessage


@property(nonatomic, readwrite, copy, null_resettable) NSData *relatedPubKey;

@property(nonatomic, readwrite) enum NCProtoChatType chatType;

@end

/**
 * Fetches the raw value of a @c NCProtoQueryRecallStatusReq's @c chatType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoQueryRecallStatusReq_ChatType_RawValue(NCProtoQueryRecallStatusReq *message);
/**
 * Sets the raw value of an @c NCProtoQueryRecallStatusReq's @c chatType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoQueryRecallStatusReq_ChatType_RawValue(NCProtoQueryRecallStatusReq *message, int32_t value);

#pragma mark - NCProtoQueryRecallStatusRsp

typedef GPB_ENUM(NCProtoQueryRecallStatusRsp_FieldNumber) {
  NCProtoQueryRecallStatusRsp_FieldNumber_FromPubKey = 1,
  NCProtoQueryRecallStatusRsp_FieldNumber_ToPubKey = 2,
  NCProtoQueryRecallStatusRsp_FieldNumber_ChatType = 3,
  NCProtoQueryRecallStatusRsp_FieldNumber_Timestamp = 4,
  NCProtoQueryRecallStatusRsp_FieldNumber_OutTradeNo = 5,
  NCProtoQueryRecallStatusRsp_FieldNumber_BizStatus = 6,
};

@interface NCProtoQueryRecallStatusRsp : GPBMessage


@property(nonatomic, readwrite, copy, null_resettable) NSData *fromPubKey;


@property(nonatomic, readwrite, copy, null_resettable) NSData *toPubKey;

/** 撤回消息类型：单聊或群聊 */
@property(nonatomic, readwrite) enum NCProtoChatType chatType;


@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *outTradeNo;

@property(nonatomic, readwrite) enum NCProtoOrderBizStatus bizStatus;

@end

/**
 * Fetches the raw value of a @c NCProtoQueryRecallStatusRsp's @c chatType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoQueryRecallStatusRsp_ChatType_RawValue(NCProtoQueryRecallStatusRsp *message);
/**
 * Sets the raw value of an @c NCProtoQueryRecallStatusRsp's @c chatType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoQueryRecallStatusRsp_ChatType_RawValue(NCProtoQueryRecallStatusRsp *message, int32_t value);

/**
 * Fetches the raw value of a @c NCProtoQueryRecallStatusRsp's @c bizStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoQueryRecallStatusRsp_BizStatus_RawValue(NCProtoQueryRecallStatusRsp *message);
/**
 * Sets the raw value of an @c NCProtoQueryRecallStatusRsp's @c bizStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoQueryRecallStatusRsp_BizStatus_RawValue(NCProtoQueryRecallStatusRsp *message, int32_t value);

#pragma mark - NCProtoRecallMsgNotify

typedef GPB_ENUM(NCProtoRecallMsgNotify_FieldNumber) {
  NCProtoRecallMsgNotify_FieldNumber_ChatType = 1,
  NCProtoRecallMsgNotify_FieldNumber_Timestamp = 2,
};


@interface NCProtoRecallMsgNotify : GPBMessage

/** 撤回消息类型：单聊或群聊 */
@property(nonatomic, readwrite) enum NCProtoChatType chatType;


@property(nonatomic, readwrite) int64_t timestamp;

@end

/**
 * Fetches the raw value of a @c NCProtoRecallMsgNotify's @c chatType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoRecallMsgNotify_ChatType_RawValue(NCProtoRecallMsgNotify *message);
/**
 * Sets the raw value of an @c NCProtoRecallMsgNotify's @c chatType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoRecallMsgNotify_ChatType_RawValue(NCProtoRecallMsgNotify *message, int32_t value);

#pragma mark - NCProtoRecallMsgFailedNotify

typedef GPB_ENUM(NCProtoRecallMsgFailedNotify_FieldNumber) {
  NCProtoRecallMsgFailedNotify_FieldNumber_ChatType = 1,
  NCProtoRecallMsgFailedNotify_FieldNumber_Timestamp = 2,
  NCProtoRecallMsgFailedNotify_FieldNumber_OutTradeNo = 3,
};

@interface NCProtoRecallMsgFailedNotify : GPBMessage

/** 撤回消息类型：单聊或群聊 */
@property(nonatomic, readwrite) enum NCProtoChatType chatType;


@property(nonatomic, readwrite) int64_t timestamp;


@property(nonatomic, readwrite, copy, null_resettable) NSString *outTradeNo;

@end

/**
 * Fetches the raw value of a @c NCProtoRecallMsgFailedNotify's @c chatType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NCProtoRecallMsgFailedNotify_ChatType_RawValue(NCProtoRecallMsgFailedNotify *message);
/**
 * Sets the raw value of an @c NCProtoRecallMsgFailedNotify's @c chatType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNCProtoRecallMsgFailedNotify_ChatType_RawValue(NCProtoRecallMsgFailedNotify *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop


