// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smscode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NCProtoSmscodeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NCProtoSmscodeRoot : GPBRootObject
@end

#pragma mark - NCProtoGetSmscodeReq

typedef GPB_ENUM(NCProtoGetSmscodeReq_FieldNumber) {
  NCProtoGetSmscodeReq_FieldNumber_Phone = 1,
  NCProtoGetSmscodeReq_FieldNumber_Token = 2,
};

@interface NCProtoGetSmscodeReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - NCProtoVerifySmscodeReq

typedef GPB_ENUM(NCProtoVerifySmscodeReq_FieldNumber) {
  NCProtoVerifySmscodeReq_FieldNumber_Smscode = 1,
};

@interface NCProtoVerifySmscodeReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *smscode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
