// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smscode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "Smscode.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - NCProtoSmscodeRoot

@implementation NCProtoSmscodeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - NCProtoSmscodeRoot_FileDescriptor

static GPBFileDescriptor *NCProtoSmscodeRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"netcloth"
                                                 objcPrefix:@"NCProto"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - NCProtoGetSmscodeReq

@implementation NCProtoGetSmscodeReq

@dynamic phone;
@dynamic token;

typedef struct NCProtoGetSmscodeReq__storage_ {
  uint32_t _has_storage_[1];
  NSString *phone;
  NSString *token;
} NCProtoGetSmscodeReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "phone",
        .dataTypeSpecific.className = NULL,
        .number = NCProtoGetSmscodeReq_FieldNumber_Phone,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NCProtoGetSmscodeReq__storage_, phone),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "token",
        .dataTypeSpecific.className = NULL,
        .number = NCProtoGetSmscodeReq_FieldNumber_Token,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(NCProtoGetSmscodeReq__storage_, token),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NCProtoGetSmscodeReq class]
                                     rootClass:[NCProtoSmscodeRoot class]
                                          file:NCProtoSmscodeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NCProtoGetSmscodeReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - NCProtoVerifySmscodeReq

@implementation NCProtoVerifySmscodeReq

@dynamic smscode;

typedef struct NCProtoVerifySmscodeReq__storage_ {
  uint32_t _has_storage_[1];
  NSString *smscode;
} NCProtoVerifySmscodeReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "smscode",
        .dataTypeSpecific.className = NULL,
        .number = NCProtoVerifySmscodeReq_FieldNumber_Smscode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NCProtoVerifySmscodeReq__storage_, smscode),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NCProtoVerifySmscodeReq class]
                                     rootClass:[NCProtoSmscodeRoot class]
                                          file:NCProtoSmscodeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NCProtoVerifySmscodeReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
